Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\romanpc> cd dev
PS C:\Users\romanpc\dev> ls


    Directory: C:\Users\romanpc\dev


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         9/8/2020  10:21 PM                cfehome
d-----       10/18/2020   2:59 PM                env
d-----       10/12/2020   7:56 PM                GitHub
d-----       10/12/2020   7:58 PM                GitHub - Copy
d-----       10/18/2020   2:45 PM                GithubBookmarksStuff
-a----       10/18/2020   2:40 PM        9320687 CIDM6325-master.zip
-a----       10/18/2020   3:31 PM        2932090 Django-3-by-Example-master.zip
-a----       10/12/2020   8:00 PM       31648439 GitHub - Assignment 4.5.rar


PS C:\Users\romanpc\dev> cd env
PS C:\Users\romanpc\dev\env> ls


    Directory: C:\Users\romanpc\dev\env


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       10/18/2020  10:43 PM                env


PS C:\Users\romanpc\dev\env> cd env
PS C:\Users\romanpc\dev\env\env> ls


    Directory: C:\Users\romanpc\dev\env\env


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       10/18/2020   9:34 PM                bookmarks
-a----       10/18/2020  10:43 PM       25056012 bookmarks.zip


PS C:\Users\romanpc\dev\env\env> python3 -m venv env/myshop
PS C:\Users\romanpc\dev\env\env> ls


    Directory: C:\Users\romanpc\dev\env\env


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       10/18/2020   9:34 PM                bookmarks
-a----       10/18/2020  10:43 PM       25056012 bookmarks.zip


PS C:\Users\romanpc\dev\env\env> ls


    Directory: C:\Users\romanpc\dev\env\env


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       10/18/2020   9:34 PM                bookmarks
-a----       10/18/2020  10:43 PM       25056012 bookmarks.zip


PS C:\Users\romanpc\dev\env\env> Python
Python 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
PS C:\Users\romanpc\dev\env\env> ls


    Directory: C:\Users\romanpc\dev\env\env


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       10/18/2020   9:34 PM                bookmarks
-a----       10/18/2020  10:43 PM       25056012 bookmarks.zip


PS C:\Users\romanpc\dev\env\env> mkdir myshop


    Directory: C:\Users\romanpc\dev\env\env


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       11/11/2020   4:38 PM                myshop


PS C:\Users\romanpc\dev\env\env> ls


    Directory: C:\Users\romanpc\dev\env\env


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       10/18/2020   9:34 PM                bookmarks
d-----       11/11/2020   4:38 PM                myshop
-a----       10/18/2020  10:43 PM       25056012 bookmarks.zip


PS C:\Users\romanpc\dev\env\env> cd myshop
PS C:\Users\romanpc\dev\env\env\myshop> virtualenv .
created virtual environment CPython3.8.5.final.0-64 in 4040ms
  creator CPython3Windows(dest=C:\Users\romanpc\Dev\env\env\myshop, clear=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\romanpc\AppData\Local\pypa\virtualenv)
    added seed packages: pip==20.2.3, setuptools==50.3.0, wheel==0.35.1
  activators BashActivator,BatchActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
PS C:\Users\romanpc\dev\env\env\myshop> ls


    Directory: C:\Users\romanpc\dev\env\env\myshop


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       11/11/2020   4:39 PM                Lib
d-----       11/11/2020   4:39 PM                Scripts
-a----       11/11/2020   4:39 PM             42 .gitignore
-a----       11/11/2020   4:39 PM            237 pyvenv.cfg


PS C:\Users\romanpc\dev\env\env\myshop> cd ..
PS C:\Users\romanpc\dev\env\env> ls


    Directory: C:\Users\romanpc\dev\env\env


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       10/18/2020   9:34 PM                bookmarks
d-----       11/11/2020   4:39 PM                myshop
-a----       10/18/2020  10:43 PM       25056012 bookmarks.zip


PS C:\Users\romanpc\dev\env\env> cd myshop
PS C:\Users\romanpc\dev\env\env\myshop> ls


    Directory: C:\Users\romanpc\dev\env\env\myshop


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       11/11/2020   4:39 PM                Lib
d-----       11/11/2020   4:39 PM                Scripts
-a----       11/11/2020   4:39 PM             42 .gitignore
-a----       11/11/2020   4:39 PM            237 pyvenv.cfg


PS C:\Users\romanpc\dev\env\env\myshop> cd .Scripts/activate
cd : Cannot find path 'C:\Users\romanpc\dev\env\env\myshop\.Scripts\activate' because it does not exist.
At line:1 char:1
+ cd .Scripts/activate
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\romanp...cripts\activate:String) [Set-Location], ItemNotFoundE
   xception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

PS C:\Users\romanpc\dev\env\env\myshop> cd Scripts
PS C:\Users\romanpc\dev\env\env\myshop\Scripts> activate
activate : The term 'activate' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ activate
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (activate:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


Suggestion [3,General]: The command activate was not found, but does exist in the current location. Windows PowerShell does not load commands from the current location by default. If you trust this command, instead type: ".\activate". See "get-help about_Command_Precedence" for more details.
PS C:\Users\romanpc\dev\env\env\myshop\Scripts> cd Scripts
cd : Cannot find path 'C:\Users\romanpc\dev\env\env\myshop\Scripts\Scripts' because it does not exist.
At line:1 char:1
+ cd Scripts
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\romanp...Scripts\Scripts:String) [Set-Location], ItemNotFoundE
   xception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

PS C:\Users\romanpc\dev\env\env\myshop\Scripts> ls


    Directory: C:\Users\romanpc\dev\env\env\myshop\Scripts


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       11/11/2020   4:39 PM           2312 activate
-a----       11/11/2020   4:39 PM           1068 activate.bat
-a----       11/11/2020   4:39 PM           3178 activate.fish
-a----       11/11/2020   4:39 PM           1815 activate.ps1
-a----       11/11/2020   4:39 PM           1215 activate.xsh
-a----       11/11/2020   4:39 PM           1225 activate_this.py
-a----       11/11/2020   4:39 PM            529 deactivate.bat
-a----       11/11/2020   4:39 PM         106374 easy_install-3.8.exe
-a----       11/11/2020   4:39 PM         106374 easy_install.exe
-a----       11/11/2020   4:39 PM         106374 easy_install3.8.exe
-a----       11/11/2020   4:39 PM         106374 easy_install3.exe
-a----       11/11/2020   4:39 PM        3399200 libcrypto-1_1.dll
-a----       11/11/2020   4:39 PM          32792 libffi-7.dll
-a----       11/11/2020   4:39 PM         689184 libssl-1_1.dll
-a----       11/11/2020   4:39 PM         106365 pip-3.8.exe
-a----       11/11/2020   4:39 PM         106365 pip.exe
-a----       11/11/2020   4:39 PM         106365 pip3.8.exe
-a----       11/11/2020   4:39 PM         106365 pip3.exe
-a----       11/11/2020   4:39 PM             25 pydoc.bat
-a----       11/11/2020   4:39 PM         189000 pyexpat.pyd
-a----       11/11/2020   4:39 PM         100424 python.exe
-a----       11/11/2020   4:39 PM          58952 python3.dll
-a----       11/11/2020   4:39 PM        4209224 python38.dll
-a----       11/11/2020   4:39 PM          98888 pythonw.exe
-a----       11/11/2020   4:39 PM          26696 select.pyd
-a----       11/11/2020   4:39 PM        1475656 sqlite3.dll
-a----       11/11/2020   4:39 PM        1705120 tcl86t.dll
-a----       11/11/2020   4:39 PM        1468064 tk86t.dll
-a----       11/11/2020   4:39 PM        1096264 unicodedata.pyd
-a----       11/11/2020   4:39 PM         101664 vcruntime140.dll
-a----       11/11/2020   4:39 PM          44328 vcruntime140_1.dll
-a----       11/11/2020   4:39 PM         106352 wheel-3.8.exe
-a----       11/11/2020   4:39 PM         106352 wheel.exe
-a----       11/11/2020   4:39 PM         106352 wheel3.8.exe
-a----       11/11/2020   4:39 PM         106352 wheel3.exe
-a----       11/11/2020   4:39 PM          29256 winsound.pyd
-a----       11/11/2020   4:39 PM          63560 _asyncio.pyd
-a----       11/11/2020   4:39 PM          86088 _bz2.pyd
-a----       11/11/2020   4:39 PM         126024 _ctypes.pyd
-a----       11/11/2020   4:39 PM          33352 _ctypes_test.pyd
-a----       11/11/2020   4:39 PM         266824 _decimal.pyd
-a----       11/11/2020   4:39 PM         177224 _elementtree.pyd
-a----       11/11/2020   4:39 PM          46152 _hashlib.pyd
-a----       11/11/2020   4:39 PM         162376 _lzma.pyd
-a----       11/11/2020   4:39 PM          38984 _msi.pyd
-a----       11/11/2020   4:39 PM          29256 _multiprocessing.pyd
-a----       11/11/2020   4:39 PM          45640 _overlapped.pyd
-a----       11/11/2020   4:39 PM          28232 _queue.pyd
-a----       11/11/2020   4:39 PM          78920 _socket.pyd
-a----       11/11/2020   4:39 PM          87624 _sqlite3.pyd
-a----       11/11/2020   4:39 PM         153672 _ssl.pyd
-a----       11/11/2020   4:39 PM          54856 _testbuffer.pyd
-a----       11/11/2020   4:39 PM         113224 _testcapi.pyd
-a----       11/11/2020   4:39 PM          24136 _testconsole.pyd
-a----       11/11/2020   4:39 PM          22088 _testimportmultiple.pyd
-a----       11/11/2020   4:39 PM          31816 _testmultiphase.pyd
-a----       11/11/2020   4:39 PM          64072 _tkinter.pyd


PS C:\Users\romanpc\dev\env\env\myshop\Scripts> activate
activate : The term 'activate' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ activate
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (activate:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


Suggestion [3,General]: The command activate was not found, but does exist in the current location. Windows PowerShell does not load commands from the current location by default. If you trust this command, instead type: ".\activate". See "get-help about_Command_Precedence" for more details.
PS C:\Users\romanpc\dev\env\env\myshop\Scripts> Python
Python 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> ls
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'ls' is not defined
>>> cd ..
  File "<stdin>", line 1
    cd ..
        ^
SyntaxError: invalid syntax
>>> Python activate
  File "<stdin>", line 1
    Python activate
           ^
SyntaxError: invalid syntax
>>> exit()
PS C:\Users\romanpc\dev\env\env\myshop\Scripts> ls


    Directory: C:\Users\romanpc\dev\env\env\myshop\Scripts


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       11/11/2020   4:39 PM           2312 activate
-a----       11/11/2020   4:39 PM           1068 activate.bat
-a----       11/11/2020   4:39 PM           3178 activate.fish
-a----       11/11/2020   4:39 PM           1815 activate.ps1
-a----       11/11/2020   4:39 PM           1215 activate.xsh
-a----       11/11/2020   4:39 PM           1225 activate_this.py
-a----       11/11/2020   4:39 PM            529 deactivate.bat
-a----       11/11/2020   4:39 PM         106374 easy_install-3.8.exe
-a----       11/11/2020   4:39 PM         106374 easy_install.exe
-a----       11/11/2020   4:39 PM         106374 easy_install3.8.exe
-a----       11/11/2020   4:39 PM         106374 easy_install3.exe
-a----       11/11/2020   4:39 PM        3399200 libcrypto-1_1.dll
-a----       11/11/2020   4:39 PM          32792 libffi-7.dll
-a----       11/11/2020   4:39 PM         689184 libssl-1_1.dll
-a----       11/11/2020   4:39 PM         106365 pip-3.8.exe
-a----       11/11/2020   4:39 PM         106365 pip.exe
-a----       11/11/2020   4:39 PM         106365 pip3.8.exe
-a----       11/11/2020   4:39 PM         106365 pip3.exe
-a----       11/11/2020   4:39 PM             25 pydoc.bat
-a----       11/11/2020   4:39 PM         189000 pyexpat.pyd
-a----       11/11/2020   4:39 PM         100424 python.exe
-a----       11/11/2020   4:39 PM          58952 python3.dll
-a----       11/11/2020   4:39 PM        4209224 python38.dll
-a----       11/11/2020   4:39 PM          98888 pythonw.exe
-a----       11/11/2020   4:39 PM          26696 select.pyd
-a----       11/11/2020   4:39 PM        1475656 sqlite3.dll
-a----       11/11/2020   4:39 PM        1705120 tcl86t.dll
-a----       11/11/2020   4:39 PM        1468064 tk86t.dll
-a----       11/11/2020   4:39 PM        1096264 unicodedata.pyd
-a----       11/11/2020   4:39 PM         101664 vcruntime140.dll
-a----       11/11/2020   4:39 PM          44328 vcruntime140_1.dll
-a----       11/11/2020   4:39 PM         106352 wheel-3.8.exe
-a----       11/11/2020   4:39 PM         106352 wheel.exe
-a----       11/11/2020   4:39 PM         106352 wheel3.8.exe
-a----       11/11/2020   4:39 PM         106352 wheel3.exe
-a----       11/11/2020   4:39 PM          29256 winsound.pyd
-a----       11/11/2020   4:39 PM          63560 _asyncio.pyd
-a----       11/11/2020   4:39 PM          86088 _bz2.pyd
-a----       11/11/2020   4:39 PM         126024 _ctypes.pyd
-a----       11/11/2020   4:39 PM          33352 _ctypes_test.pyd
-a----       11/11/2020   4:39 PM         266824 _decimal.pyd
-a----       11/11/2020   4:39 PM         177224 _elementtree.pyd
-a----       11/11/2020   4:39 PM          46152 _hashlib.pyd
-a----       11/11/2020   4:39 PM         162376 _lzma.pyd
-a----       11/11/2020   4:39 PM          38984 _msi.pyd
-a----       11/11/2020   4:39 PM          29256 _multiprocessing.pyd
-a----       11/11/2020   4:39 PM          45640 _overlapped.pyd
-a----       11/11/2020   4:39 PM          28232 _queue.pyd
-a----       11/11/2020   4:39 PM          78920 _socket.pyd
-a----       11/11/2020   4:39 PM          87624 _sqlite3.pyd
-a----       11/11/2020   4:39 PM         153672 _ssl.pyd
-a----       11/11/2020   4:39 PM          54856 _testbuffer.pyd
-a----       11/11/2020   4:39 PM         113224 _testcapi.pyd
-a----       11/11/2020   4:39 PM          24136 _testconsole.pyd
-a----       11/11/2020   4:39 PM          22088 _testimportmultiple.pyd
-a----       11/11/2020   4:39 PM          31816 _testmultiphase.pyd
-a----       11/11/2020   4:39 PM          64072 _tkinter.pyd


PS C:\Users\romanpc\dev\env\env\myshop\Scripts> cd ..
PS C:\Users\romanpc\dev\env\env\myshop> ls


    Directory: C:\Users\romanpc\dev\env\env\myshop


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       11/11/2020   4:39 PM                Lib
d-----       11/11/2020   4:39 PM                Scripts
-a----       11/11/2020   4:39 PM             42 .gitignore
-a----       11/11/2020   4:39 PM            237 pyvenv.cfg


PS C:\Users\romanpc\dev\env\env\myshop> ./Scripts/activate
(myshop) PS C:\Users\romanpc\dev\env\env\myshop> pip install "Django==3.0.*"
Collecting Django==3.0.*
  Downloading Django-3.0.11-py3-none-any.whl (7.5 MB)
     |████████████████████████████████| 7.5 MB 2.2 MB/s
Collecting asgiref~=3.2
  Downloading asgiref-3.3.1-py3-none-any.whl (19 kB)
Collecting pytz
  Downloading pytz-2020.4-py2.py3-none-any.whl (509 kB)
     |████████████████████████████████| 509 kB 6.8 MB/s
Collecting sqlparse>=0.2.2
  Using cached sqlparse-0.4.1-py3-none-any.whl (42 kB)
Installing collected packages: asgiref, pytz, sqlparse, Django
Successfully installed Django-3.0.11 asgiref-3.3.1 pytz-2020.4 sqlparse-0.4.1
WARNING: You are using pip version 20.2.3; however, version 20.2.4 is available.
You should consider upgrading via the 'C:\Users\romanpc\Dev\env\env\myshop\Scripts\python.exe -m pip install --upgrade pip' command.
(myshop) PS C:\Users\romanpc\dev\env\env\myshop> django-admin startproject myshop
(myshop) PS C:\Users\romanpc\dev\env\env\myshop> ls


    Directory: C:\Users\romanpc\dev\env\env\myshop


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       11/11/2020   4:39 PM                Lib
d-----       11/11/2020   4:41 PM                myshop
d-----       11/11/2020   4:41 PM                Scripts
-a----       11/11/2020   4:39 PM             42 .gitignore
-a----       11/11/2020   4:39 PM            237 pyvenv.cfg


(myshop) PS C:\Users\romanpc\dev\env\env\myshop> cd myshop/
(myshop) PS C:\Users\romanpc\dev\env\env\myshop\myshop> django-admin startapp shop
(myshop) PS C:\Users\romanpc\dev\env\env\myshop\myshop> pip install Pillow==7.0.0
Collecting Pillow==7.0.0
  Using cached Pillow-7.0.0-cp38-cp38-win_amd64.whl (2.0 MB)
Installing collected packages: Pillow
Successfully installed Pillow-7.0.0
WARNING: You are using pip version 20.2.3; however, version 20.2.4 is available.
You should consider upgrading via the 'C:\Users\romanpc\Dev\env\env\myshop\Scripts\python.exe -m pip install --upgrade pip' command.
(myshop) PS C:\Users\romanpc\dev\env\env\myshop\myshop> python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\__init__.py", line 377, in execute
    django.setup()
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\apps\config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "c:\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\romanpc\dev\env\env\myshop\myshop\shop\models.py", line 36
    return self.name
    ^
IndentationError: expected an indented block
(myshop) PS C:\Users\romanpc\dev\env\env\myshop\myshop> python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\__init__.py", line 377, in execute
    django.setup()
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\apps\config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "c:\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\romanpc\dev\env\env\myshop\myshop\shop\models.py", line 36
    return self.name
    ^
IndentationError: expected an indented block
(myshop) PS C:\Users\romanpc\dev\env\env\myshop\myshop> python manage.py makemigrations
Migrations for 'shop':
  shop\migrations\0001_initial.py
    - Create model Category
    - Create model Product
(myshop) PS C:\Users\romanpc\dev\env\env\myshop\myshop> python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions, shop
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying sessions.0001_initial... OK
  Applying shop.0001_initial... OK
(myshop) PS C:\Users\romanpc\dev\env\env\myshop\myshop> python manage.py createsuperuser
SystemCheckError: System check identified some issues:

ERRORS:
<class 'shop.admin.CategoryAdmin'>: (admin.E108) The value of 'list_display[0]' refers to 'namme', which is not a callable, an attribute of 'CategoryAdmin', or an attribute or method on 'shop.Category'.
<class 'shop.admin.ProductAdmin'>: (admin.E108) The value of 'list_display[2]' refers to 'price', which is not a callable, an attribute of 'ProductAdmin', or an attribute or method on 'shop.Product'.
<class 'shop.admin.ProductAdmin'>: (admin.E108) The value of 'list_display[3]' refers to 'available', which is not a callable, an attribute of 'ProductAdmin', or an attribute or method on 'shop.Product'.
<class 'shop.admin.ProductAdmin'>: (admin.E108) The value of 'list_display[4]' refers to 'created', which is not a callable, an attribute of 'ProductAdmin', or an attribute or method on 'shop.Product'.
<class 'shop.admin.ProductAdmin'>: (admin.E108) The value of 'list_display[5]' refers to 'updated', which is not a callable, an attribute of 'ProductAdmin', or an attribute or method on 'shop.Product'.
<class 'shop.admin.ProductAdmin'>: (admin.E116) The value of 'list_filter[0]' refers to 'available', which does not refer to a Field.
<class 'shop.admin.ProductAdmin'>: (admin.E116) The value of 'list_filter[1]' refers to 'created', which does not refer to a Field.
<class 'shop.admin.ProductAdmin'>: (admin.E116) The value of 'list_filter[2]' refers to 'updated', which does not refer to a Field.
<class 'shop.admin.ProductAdmin'>: (admin.E121) The value of 'list_editable[0]' refers to 'price', which is not an attribute of 'shop.Product'.
<class 'shop.admin.ProductAdmin'>: (admin.E121) The value of 'list_editable[1]' refers to 'available', which is not an attribute of 'shop.Product'.
(myshop) PS C:\Users\romanpc\dev\env\env\myshop\myshop> python manage.py createsuperuser
SystemCheckError: System check identified some issues:

ERRORS:
<class 'shop.admin.ProductAdmin'>: (admin.E108) The value of 'list_display[2]' refers to 'price', which is not a callable, an attribute of 'ProductAdmin', or an attribute or method on 'shop.Product'.
<class 'shop.admin.ProductAdmin'>: (admin.E108) The value of 'list_display[3]' refers to 'available', which is not a callable, an attribute of 'ProductAdmin', or an attribute or method on 'shop.Product'.
<class 'shop.admin.ProductAdmin'>: (admin.E108) The value of 'list_display[4]' refers to 'created', which is not a callable, an attribute of 'ProductAdmin', or an attribute or method on 'shop.Product'.
<class 'shop.admin.ProductAdmin'>: (admin.E108) The value of 'list_display[5]' refers to 'updated', which is not a callable, an attribute of 'ProductAdmin', or an attribute or method on 'shop.Product'.
<class 'shop.admin.ProductAdmin'>: (admin.E116) The value of 'list_filter[0]' refers to 'available', which does not refer to a Field.
<class 'shop.admin.ProductAdmin'>: (admin.E116) The value of 'list_filter[1]' refers to 'created', which does not refer to a Field.
<class 'shop.admin.ProductAdmin'>: (admin.E116) The value of 'list_filter[2]' refers to 'updated', which does not refer to a Field.
<class 'shop.admin.ProductAdmin'>: (admin.E121) The value of 'list_editable[0]' refers to 'price', which is not an attribute of 'shop.Product'.
<class 'shop.admin.ProductAdmin'>: (admin.E121) The value of 'list_editable[1]' refers to 'available', which is not an attribute of 'shop.Product'.
(myshop) PS C:\Users\romanpc\dev\env\env\myshop\myshop> python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "c:\python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "c:\python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\commands\runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\base.py", line 441, in check
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
<class 'shop.admin.ProductAdmin'>: (admin.E108) The value of 'list_display[2]' refers to 'price', which is not a callable, an attribute of 'ProductAdmin', or an attribute or method on 'shop.Product'.
<class 'shop.admin.ProductAdmin'>: (admin.E108) The value of 'list_display[3]' refers to 'available', which is not a callable, an attribute of 'ProductAdmin', or an attribute or method on 'shop.Product'.
<class 'shop.admin.ProductAdmin'>: (admin.E108) The value of 'list_display[4]' refers to 'created', which is not a callable, an attribute of 'ProductAdmin', or an attribute or method on 'shop.Product'.
<class 'shop.admin.ProductAdmin'>: (admin.E108) The value of 'list_display[5]' refers to 'updated', which is not a callable, an attribute of 'ProductAdmin', or an attribute or method on 'shop.Product'.
<class 'shop.admin.ProductAdmin'>: (admin.E116) The value of 'list_filter[0]' refers to 'available', which does not refer to a Field.
<class 'shop.admin.ProductAdmin'>: (admin.E116) The value of 'list_filter[1]' refers to 'created', which does not refer to a Field.
<class 'shop.admin.ProductAdmin'>: (admin.E116) The value of 'list_filter[2]' refers to 'updated', which does not refer to a Field.
<class 'shop.admin.ProductAdmin'>: (admin.E121) The value of 'list_editable[0]' refers to 'price', which is not an attribute of 'shop.Product'.
<class 'shop.admin.ProductAdmin'>: (admin.E121) The value of 'list_editable[1]' refers to 'available', which is not an attribute of 'shop.Product'.

System check identified 9 issues (0 silenced).
(myshop) PS C:\Users\romanpc\dev\env\env\myshop\myshop> python manage.py migrate
SystemCheckError: System check identified some issues:

ERRORS:
<class 'shop.admin.ProductAdmin'>: (admin.E108) The value of 'list_display[2]' refers to 'price', which is not a callable, an attribute of 'ProductAdmin', or an attribute or method on 'shop.Product'.
<class 'shop.admin.ProductAdmin'>: (admin.E108) The value of 'list_display[3]' refers to 'available', which is not a callable, an attribute of 'ProductAdmin', or an attribute or method on 'shop.Product'.
<class 'shop.admin.ProductAdmin'>: (admin.E108) The value of 'list_display[4]' refers to 'created', which is not a callable, an attribute of 'ProductAdmin', or an attribute or method on 'shop.Product'.
<class 'shop.admin.ProductAdmin'>: (admin.E108) The value of 'list_display[5]' refers to 'updated', which is not a callable, an attribute of 'ProductAdmin', or an attribute or method on 'shop.Product'.
<class 'shop.admin.ProductAdmin'>: (admin.E116) The value of 'list_filter[0]' refers to 'available', which does not refer to a Field.
<class 'shop.admin.ProductAdmin'>: (admin.E116) The value of 'list_filter[1]' refers to 'created', which does not refer to a Field.
<class 'shop.admin.ProductAdmin'>: (admin.E116) The value of 'list_filter[2]' refers to 'updated', which does not refer to a Field.
<class 'shop.admin.ProductAdmin'>: (admin.E121) The value of 'list_editable[0]' refers to 'price', which is not an attribute of 'shop.Product'.
<class 'shop.admin.ProductAdmin'>: (admin.E121) The value of 'list_editable[1]' refers to 'available', which is not an attribute of 'shop.Product'.
(myshop) PS C:\Users\romanpc\dev\env\env\myshop\myshop> python manage.py makemigrations
SystemCheckError: System check identified some issues:

ERRORS:
<class 'shop.admin.ProductAdmin'>: (admin.E108) The value of 'list_display[2]' refers to 'price', which is not a callable, an attribute of 'ProductAdmin', or an attribute or method on 'shop.Product'.
<class 'shop.admin.ProductAdmin'>: (admin.E108) The value of 'list_display[3]' refers to 'available', which is not a callable, an attribute of 'ProductAdmin', or an attribute or method on 'shop.Product'.
<class 'shop.admin.ProductAdmin'>: (admin.E108) The value of 'list_display[4]' refers to 'created', which is not a callable, an attribute of 'ProductAdmin', or an attribute or method on 'shop.Product'.
<class 'shop.admin.ProductAdmin'>: (admin.E108) The value of 'list_display[5]' refers to 'updated', which is not a callable, an attribute of 'ProductAdmin', or an attribute or method on 'shop.Product'.
<class 'shop.admin.ProductAdmin'>: (admin.E116) The value of 'list_filter[0]' refers to 'available', which does not refer to a Field.
<class 'shop.admin.ProductAdmin'>: (admin.E116) The value of 'list_filter[1]' refers to 'created', which does not refer to a Field.
<class 'shop.admin.ProductAdmin'>: (admin.E116) The value of 'list_filter[2]' refers to 'updated', which does not refer to a Field.
<class 'shop.admin.ProductAdmin'>: (admin.E121) The value of 'list_editable[0]' refers to 'price', which is not an attribute of 'shop.Product'.
<class 'shop.admin.ProductAdmin'>: (admin.E121) The value of 'list_editable[1]' refers to 'available', which is not an attribute of 'shop.Product'.
(myshop) PS C:\Users\romanpc\dev\env\env\myshop\myshop> python manage.py createsuperuser
SystemCheckError: System check identified some issues:

ERRORS:
<class 'shop.admin.ProductAdmin'>: (admin.E108) The value of 'list_display[2]' refers to 'price', which is not a callable, an attribute of 'ProductAdmin', or an attribute or method on 'shop.Product'.
<class 'shop.admin.ProductAdmin'>: (admin.E108) The value of 'list_display[3]' refers to 'available', which is not a callable, an attribute of 'ProductAdmin', or an attribute or method on 'shop.Product'.
<class 'shop.admin.ProductAdmin'>: (admin.E108) The value of 'list_display[4]' refers to 'created', which is not a callable, an attribute of 'ProductAdmin', or an attribute or method on 'shop.Product'.
<class 'shop.admin.ProductAdmin'>: (admin.E108) The value of 'list_display[5]' refers to 'updated', which is not a callable, an attribute of 'ProductAdmin', or an attribute or method on 'shop.Product'.
<class 'shop.admin.ProductAdmin'>: (admin.E116) The value of 'list_filter[0]' refers to 'available', which does not refer to a Field.
<class 'shop.admin.ProductAdmin'>: (admin.E116) The value of 'list_filter[1]' refers to 'created', which does not refer to a Field.
<class 'shop.admin.ProductAdmin'>: (admin.E116) The value of 'list_filter[2]' refers to 'updated', which does not refer to a Field.
<class 'shop.admin.ProductAdmin'>: (admin.E121) The value of 'list_editable[0]' refers to 'price', which is not an attribute of 'shop.Product'.
<class 'shop.admin.ProductAdmin'>: (admin.E121) The value of 'list_editable[1]' refers to 'available', which is not an attribute of 'shop.Product'.
(myshop) PS C:\Users\romanpc\dev\env\env\myshop\myshop> python manage.py createsuperuser
SystemCheckError: System check identified some issues:

ERRORS:
<class 'shop.admin.ProductAdmin'>: (admin.E108) The value of 'list_display[2]' refers to 'price', which is not a callable, an attribute of 'ProductAdmin', or an attribute or method on 'shop.Product'.
<class 'shop.admin.ProductAdmin'>: (admin.E108) The value of 'list_display[3]' refers to 'available', which is not a callable, an attribute of 'ProductAdmin', or an attribute or method on 'shop.Product'.
<class 'shop.admin.ProductAdmin'>: (admin.E108) The value of 'list_display[4]' refers to 'created', which is not a callable, an attribute of 'ProductAdmin', or an attribute or method on 'shop.Product'.
<class 'shop.admin.ProductAdmin'>: (admin.E108) The value of 'list_display[5]' refers to 'updated', which is not a callable, an attribute of 'ProductAdmin', or an attribute or method on 'shop.Product'.
<class 'shop.admin.ProductAdmin'>: (admin.E116) The value of 'list_filter[0]' refers to 'available', which does not refer to a Field.
<class 'shop.admin.ProductAdmin'>: (admin.E116) The value of 'list_filter[1]' refers to 'created', which does not refer to a Field.
<class 'shop.admin.ProductAdmin'>: (admin.E116) The value of 'list_filter[2]' refers to 'updated', which does not refer to a Field.
<class 'shop.admin.ProductAdmin'>: (admin.E121) The value of 'list_editable[0]' refers to 'price', which is not an attribute of 'shop.Product'.
<class 'shop.admin.ProductAdmin'>: (admin.E121) The value of 'list_editable[1]' refers to 'available', which is not an attribute of 'shop.Product'.
(myshop) PS C:\Users\romanpc\dev\env\env\myshop\myshop> python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\conf\__init__.py", line 76, in __getattr__
    self._setup(name)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\conf\__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\conf\__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "c:\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\romanpc\dev\env\env\myshop\myshop\myshop\settings.py", line 124
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media/)
                                               ^
SyntaxError: EOL while scanning string literal
(myshop) PS C:\Users\romanpc\dev\env\env\myshop\myshop> python manage.py startapp cart
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\conf\__init__.py", line 76, in __getattr__
    self._setup(name)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\conf\__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\conf\__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "c:\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\romanpc\dev\env\env\myshop\myshop\myshop\settings.py", line 124
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media/)
                                               ^
SyntaxError: EOL while scanning string literal
(myshop) PS C:\Users\romanpc\dev\env\env\myshop\myshop> python manage.py startapp cart
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\__init__.py", line 377, in execute
    django.setup()
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\apps\config.py", line 116, in create
    mod = import_module(mod_path)
  File "c:\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'cart'
(myshop) PS C:\Users\romanpc\dev\env\env\myshop\myshop> python manage.py startapp cart
(myshop) PS C:\Users\romanpc\dev\env\env\myshop\myshop> python manage.py runserver
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "c:\python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "c:\python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\commands\runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\utils\autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\apps\config.py", line 116, in create
    mod = import_module(mod_path)
  File "c:\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'orders'
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\commands\runserver.py", line 60, in execute
    super().execute(*args, **options)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\commands\runserver.py", line 95, in handle
    self.run(**options)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\commands\runserver.py", line 102, in run
    autoreload.run_with_reloader(self.inner_run, **options)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\utils\autoreload.py", line 599, in run_with_reloader
    start_django(reloader, main_func, *args, **kwargs)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\utils\autoreload.py", line 584, in start_django
    reloader.run(django_main_thread)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\utils\autoreload.py", line 299, in run
    self.run_loop()
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\utils\autoreload.py", line 305, in run_loop
    next(ticker)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\utils\autoreload.py", line 345, in tick
    for filepath, mtime in self.snapshot_files():
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\utils\autoreload.py", line 361, in snapshot_files
    for file in self.watched_files():
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\utils\autoreload.py", line 260, in watched_files
    yield from iter_all_python_module_files()
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\utils\autoreload.py", line 105, in iter_all_python_module_files
    return iter_modules_and_files(modules, frozenset(_error_files))
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\utils\autoreload.py", line 141, in iter_modules_and_files
    resolved_path = path.resolve(strict=True).absolute()
  File "c:\python38\lib\pathlib.py", line 1177, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "c:\python38\lib\pathlib.py", line 200, in resolve
    return self._ext_to_normal(_getfinalpathname(s))
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '<frozen importlib._bootstrap>'
(myshop) PS C:\Users\romanpc\dev\env\env\myshop\myshop> python manage.py runserver
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "c:\python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "c:\python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\commands\runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\utils\autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\apps\config.py", line 116, in create
    mod = import_module(mod_path)
  File "c:\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'orders'
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\commands\runserver.py", line 60, in execute
    super().execute(*args, **options)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\commands\runserver.py", line 95, in handle
    self.run(**options)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\commands\runserver.py", line 102, in run
    autoreload.run_with_reloader(self.inner_run, **options)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\utils\autoreload.py", line 599, in run_with_reloader
    start_django(reloader, main_func, *args, **kwargs)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\utils\autoreload.py", line 584, in start_django
    reloader.run(django_main_thread)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\utils\autoreload.py", line 299, in run
    self.run_loop()
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\utils\autoreload.py", line 305, in run_loop
    next(ticker)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\utils\autoreload.py", line 345, in tick
    for filepath, mtime in self.snapshot_files():
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\utils\autoreload.py", line 361, in snapshot_files
    for file in self.watched_files():
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\utils\autoreload.py", line 260, in watched_files
    yield from iter_all_python_module_files()
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\utils\autoreload.py", line 105, in iter_all_python_module_files
    return iter_modules_and_files(modules, frozenset(_error_files))
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\utils\autoreload.py", line 141, in iter_modules_and_files
    resolved_path = path.resolve(strict=True).absolute()
  File "c:\python38\lib\pathlib.py", line 1177, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "c:\python38\lib\pathlib.py", line 200, in resolve
    return self._ext_to_normal(_getfinalpathname(s))
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '<frozen importlib._bootstrap>'
(myshop) PS C:\Users\romanpc\dev\env\env\myshop\myshop> python manage.py runserver
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "c:\python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "c:\python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\commands\runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\utils\autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\apps\config.py", line 116, in create
    mod = import_module(mod_path)
  File "c:\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'orders'
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\commands\runserver.py", line 60, in execute
    super().execute(*args, **options)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\commands\runserver.py", line 95, in handle
    self.run(**options)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\commands\runserver.py", line 102, in run
    autoreload.run_with_reloader(self.inner_run, **options)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\utils\autoreload.py", line 599, in run_with_reloader
    start_django(reloader, main_func, *args, **kwargs)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\utils\autoreload.py", line 584, in start_django
    reloader.run(django_main_thread)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\utils\autoreload.py", line 299, in run
    self.run_loop()
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\utils\autoreload.py", line 305, in run_loop
    next(ticker)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\utils\autoreload.py", line 345, in tick
    for filepath, mtime in self.snapshot_files():
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\utils\autoreload.py", line 361, in snapshot_files
    for file in self.watched_files():
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\utils\autoreload.py", line 260, in watched_files
    yield from iter_all_python_module_files()
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\utils\autoreload.py", line 105, in iter_all_python_module_files
    return iter_modules_and_files(modules, frozenset(_error_files))
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\utils\autoreload.py", line 141, in iter_modules_and_files
    resolved_path = path.resolve(strict=True).absolute()
  File "c:\python38\lib\pathlib.py", line 1177, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "c:\python38\lib\pathlib.py", line 200, in resolve
    return self._ext_to_normal(_getfinalpathname(s))
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '<frozen importlib._bootstrap>'
(myshop) PS C:\Users\romanpc\dev\env\env\myshop\myshop> python manage.py startapp orders
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\core\management\__init__.py", line 377, in execute
    django.setup()
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\romanpc\dev\env\env\myshop\lib\site-packages\django\apps\config.py", line 116, in create
    mod = import_module(mod_path)
  File "c:\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'orders'
(myshop) PS C:\Users\romanpc\dev\env\env\myshop\myshop> pip install celery==4.4.2
Collecting celery==4.4.2
  Downloading celery-4.4.2-py2.py3-none-any.whl (422 kB)
     |████████████████████████████████| 422 kB 2.2 MB/s
Collecting billiard<4.0,>=3.6.3.0
  Downloading billiard-3.6.3.0-py3-none-any.whl (89 kB)
     |████████████████████████████████| 89 kB 4.2 MB/s
Collecting kombu<4.7,>=4.6.8
  Downloading kombu-4.6.11-py2.py3-none-any.whl (184 kB)
     |████████████████████████████████| 184 kB ...
Collecting vine==1.3.0
  Downloading vine-1.3.0-py2.py3-none-any.whl (14 kB)
Requirement already satisfied: pytz>dev in c:\users\romanpc\dev\env\env\myshop\lib\site-packages (from celery==4.4.2) (2020.4)
Collecting amqp<2.7,>=2.6.0
  Downloading amqp-2.6.1-py2.py3-none-any.whl (48 kB)
     |████████████████████████████████| 48 kB 2.3 MB/s
Installing collected packages: billiard, vine, amqp, kombu, celery
Successfully installed amqp-2.6.1 billiard-3.6.3.0 celery-4.4.2 kombu-4.6.11 vine-1.3.0
WARNING: You are using pip version 20.2.3; however, version 20.2.4 is available.
You should consider upgrading via the 'C:\Users\romanpc\Dev\env\env\myshop\Scripts\python.exe -m pip install --upgrade pip' command.
(myshop) PS C:\Users\romanpc\dev\env\env\myshop\myshop> apt-get install rabbitmq
apt-get : The term 'apt-get' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ apt-get install rabbitmq
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (apt-get:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

(myshop) PS C:\Users\romanpc\dev\env\env\myshop\myshop> rabbitmq-server
rabbitmq-server : The term 'rabbitmq-server' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At line:1 char:1
+ rabbitmq-server
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (rabbitmq-server:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

(myshop) PS C:\Users\romanpc\dev\env\env\myshop\myshop>